project_id = "cvyidqbjjkfzoxykkbea"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[auth]
enabled = true
site_url = "bellwire://auth/callback"
additional_redirect_urls = ["bellwire://auth/callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
